# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45129634545d9d67151deb5f87a9a5bfac01fb6aed83125e4a66dea647709bee393140d1961cf1c3859c93e4f93050de75fadb0a405a8f8622b79c20c54d6c70

test:
  secret_key_base: 1b08701c005d6c8dada44debee851b48cf6df9e82165d78ae8387778bf88cd7798e2aca1cd68291de399d91eea1ce5d6accee4f1cf56a1b99403ca1151649dab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
